### ISSUE TITLE
Can not access extension page

### ISSUE THREAD

**Issue by kravchenkodev** [auth0-extensions/auth0-gitlab-deploy#26]
After installation and configuring extension in Auth0 dashboard I get this error when try to go to extension's page. This happens with 2.4.0 version of extension
```
{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'gitlab@3.4.2'",
  "error": "Cannot find module 'gitlab@3.4.2'",
  "stack": "Error: Cannot find module 'gitlab@3.4.2'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:49:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)\n    at require (/data/sandbox/lib/module.js:136:21)\n    at Object.<anonymous> (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:82983)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at Object.module.exports.n (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:7344)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:56163)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at Object.module.exports.e.__esModule.default (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:58275)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at Object.module.exports.e.__esModule.default (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:63455)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:27201)\n    at Object.<anonymous> (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:28636)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:65703)\n    at t (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:177)\n    at /data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:560\n    at Object.<anonymous> (/data/io/f2df94e3-0805-4da2-95d3-27897c1ad2f4/webtask.js:1:571)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)\n    at /data/sandbox/lib/compiler.js:231:17\n    at /data/sandbox/node_modules/async/dist/async.js:3866:24\n    at replenish (/data/sandbox/node_modules/async/dist/async.js:998:17)\n    at iterateeCallback (/data/sandbox/node_modules/async/dist/async.js:983:17)"
}
```

Same issue replicates using another Auth0 tenant.

**Comment by fyockm** [comment]
Admittedly, this should be better documented- the Gitlab extension only works with Node 8 because of dependencies in `gitlab@3`. Please update according to [Migration Guide: Extensibility and Node 8](https://auth0.com/docs/migrations/guides/extensibility-node8).

**Comment by fyockm** [comment]
Just added a [note to readme](https://github.com/auth0-extensions/auth0-gitlab-deploy/commit/d4eabf8a7cf5c5a5f1f9e2ac21f307d90c28b8d7)

**Comment by kravchenkodev** [comment]
@fyockm Thank you!
